### ISSUE TITLE
Failed protection scan on some PC discs

### ISSUE THREAD

**Issue by superg** [SabreTools/DICUI#184]
I'm getting an exception when I dump some PC discs, !submissionInfo.txt:
`Common Disc Info:
	Title: Tomb Raider III: Adventures of Lara Croft
	System: IBM PC Compatible
	Media Type: CD-ROM
	Category: Games
	Region: USA
	Languages: English

	Ringcode Information:
		Mastering Code (laser branded/etched): ADS ADVANCED DUPLICATION SERVICES. INC.	2538-CD-0019
		Mastering SID Code: IFPI LK15
		Label-Side Mould SID Code: IFPI L8I6
	Barcode: 6 96055 10543 4
	Error Count: 0

Version and Editions:
	Edition/Release: The Trilogy

Extras:
	Primary Volume Descriptor (PVD):

0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 32 30 30                200
0330 : 31 31 32 30 35 31 30 35  33 30 30 30 30 E0 32 30   1120510530000.20
0340 : 30 31 31 32 30 35 31 30  35 33 30 30 30 30 E0 30   01120510530000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

Copy Protection:
	Copy Protection:

Path could not be scanned! System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileSystemEnumerableIterator`1.CommonInit()

   at System.IO.FileSystemEnumerableIterator`1..ctor(String fullPath, String normalizedSearchPath, String searchCriteria, String userPath, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)

   at System.IO.FileSystemEnumerableIterator`1.Clone()

   at System.IO.Iterator`1.GetEnumerator()

   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

   at BurnOutSharp.ProtectionFind.Scan(String path, IProgress`1 progress)

   at DICUI.Utilities.Validators.<>c__DisplayClass6_0.<RunProtectionScanOnPath>b__1() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:line 942

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at DICUI.Utilities.Validators.<RunProtectionScanOnPath>d__6.MoveNext() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:line 940

Tracks and Write Offsets:
	DAT:

<rom name="Tomb Raider III - Adventures of Lara Croft (USA) (Rerelease) (20011205).bin" size="561020208" crc="8d1d673f" md5="d40b30fd01c33c76ea615625f48c45e6" sha1="4980443176fc62dbbbcba1472bcba61cb398092c" />

	Cuesheet:

FILE "Tomb Raider III - Adventures of Lara Croft (USA) (Rerelease) (20011205).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

	Write Offset: -153
`

**Comment by Dimensional** [comment]
Are you running DICUI from DotNet Framework, like 4.7, or DotNet Core 3? I got a similar issue when running the DotNet Core 3, but not the Framework version.

**Comment by superg** [comment]
As far as I remember I'm just using the latest binary I downloaded from redump link, not sure which dotnet implementation is used as I have both installed.

**Comment by mnadareski** [comment]
.NET Core 3.0 build is not fully functional due to one of the necessary packages not being fully compatible.
This is something that has occurred sporadically with BurnOutSharp on some people running Windows 7 computers. I don't have access to one to test, so I can't confirm. I have no idea why it's doing this but it does happen. I'm leaving this open for now, technically should go on the BOS issues

**Comment by mnadareski** [comment]
Possibly related to https://github.com/SabreTools/DICUI/issues/169

**Comment by mnadareski** [comment]
Closing as intermittent and near-impossible to diagnose or repeat.
