### ISSUE TITLE
Copy Protection description is an IO Exception

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/DICUI#211]
For this disc: http://redump.org/disc/10743/
The copy protection is listed as an IO Exception. Unsure if this is a bug but thought I'd submit to be safe.

Copy Protection:
	Copy Protection:

Path could not be scanned! System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileSystemEnumerableIterator`1.MoveNext()

   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)

   at BurnOutSharp.ProtectionType.AACS.CheckPath(String path, IEnumerable`1 files, Boolean isDirectory)

   at BurnOutSharp.ProtectionFind.ScanPath(String path, Boolean isDirectory)

   at BurnOutSharp.ProtectionFind.Scan(String path, IProgress`1 progress)

   at DICUI.Utilities.Validators.<>c__DisplayClass6_0.<RunProtectionScanOnPath>b__2() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:line 1012

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at DICUI.Utilities.Validators.<RunProtectionScanOnPath>d__6.MoveNext() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:line 1010

**Comment by mnadareski** [comment]
This error happens on a couple of occasions:
- The disc was removed before the copy protection scan was done
- The drive was disconnected before the copy protection scan was done
- The path was somehow unreadable on Windows (for one of the systems that includes copy protection scan, like IBM PC)
